#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pillow
Version  : 4.3.0
Release  : 40
URL      : http://pypi.debian.net/Pillow/Pillow-4.3.0.tar.gz
Source0  : http://pypi.debian.net/Pillow/Pillow-4.3.0.tar.gz
Summary  : Python Imaging Library (Fork)
Group    : Development/Tools
License  : HPND OFL-1.1
Requires: Pillow-bin
Requires: Pillow-legacypython
Requires: Pillow-python
Requires: Babel
Requires: MarkupSafe
Requires: Pygments
Requires: alabaster
Requires: cov-core
Requires: coverage
Requires: nose
Requires: olefile
Requires: pyflakes
Requires: pytz
Requires: requests
Requires: six
Requires: snowballstemmer
BuildRequires : freetype-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : nose
BuildRequires : nose-python
BuildRequires : olefile
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(zlib)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
======
        
        Python Imaging Library (Fork)
        -----------------------------

%package bin
Summary: bin components for the Pillow package.
Group: Binaries

%description bin
bin components for the Pillow package.


%package legacypython
Summary: legacypython components for the Pillow package.
Group: Default

%description legacypython
legacypython components for the Pillow package.


%package python
Summary: python components for the Pillow package.
Group: Default
Requires: Pillow-legacypython
Provides: pillow-python

%description python
python components for the Pillow package.


%prep
%setup -q -n Pillow-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506969865
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1506969865
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/enhancer.py
/usr/bin/explode.py
/usr/bin/gifmaker.py
/usr/bin/painter.py
/usr/bin/pilconvert.py
/usr/bin/pildriver.py
/usr/bin/pilfile.py
/usr/bin/pilfont.py
/usr/bin/pilprint.py
/usr/bin/player.py
/usr/bin/thresholder.py
/usr/bin/viewer.py

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
