#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pillow
Version  : 8.1.0
Release  : 70
URL      : https://files.pythonhosted.org/packages/73/59/3192bb3bc554ccbd678bdb32993928cb566dccf32f65dac65ac7e89eb311/Pillow-8.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/73/59/3192bb3bc554ccbd678bdb32993928cb566dccf32f65dac65ac7e89eb311/Pillow-8.1.0.tar.gz
Summary  : Python Imaging Library (Fork)
Group    : Development/Tools
License  : HPND NTP
Requires: Pillow-license = %{version}-%{release}
Requires: Pillow-python = %{version}-%{release}
Requires: Pillow-python3 = %{version}-%{release}
Requires: black
Requires: check-manifest
Requires: olefile
Requires: packaging
Requires: pyroma
BuildRequires : black
BuildRequires : buildreq-distutils3
BuildRequires : check-manifest
BuildRequires : freetype-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : nose
BuildRequires : nose-python
BuildRequires : olefile
BuildRequires : packaging
BuildRequires : pkgconfig(zlib)
BuildRequires : pyroma
BuildRequires : zlib-dev
Patch1: Fix-build-libdir.patch

%description
<p align="center">
<img width="248" height="250" src="https://raw.githubusercontent.com/python-pillow/pillow-logo/master/pillow-logo-248x250.png" alt="Pillow logo">
</p>

%package license
Summary: license components for the Pillow package.
Group: Default

%description license
license components for the Pillow package.


%package python
Summary: python components for the Pillow package.
Group: Default
Requires: Pillow-python3 = %{version}-%{release}
Provides: pillow-python

%description python
python components for the Pillow package.


%package python3
Summary: python3 components for the Pillow package.
Group: Default
Requires: python3-core
Provides: pypi(pillow)

%description python3
python3 components for the Pillow package.


%prep
%setup -q -n Pillow-8.1.0
cd %{_builddir}/Pillow-8.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609779867
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Pillow
cp %{_builddir}/Pillow-8.1.0/Tests/icc/LICENSE.txt %{buildroot}/usr/share/package-licenses/Pillow/371117588643c602bb8f15b280424e938c34c369
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Pillow/371117588643c602bb8f15b280424e938c34c369

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
